TARGET_DIR="${1:-$HOME/.config/opencode/agents}"
SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"

[ -e "$TARGET_DIR/Orchestrator.md" ] && rm "$TARGET_DIR/Orchestrator.md"
# [ -e "$TARGET_DIR/builder.md" ] && rm "$TARGET_DIR/builder.md"
[ -e "$TARGET_DIR/coder.md" ] && rm "$TARGET_DIR/coder.md"
[ -e "$TARGET_DIR/external-context-gatherer.md" ] && rm "$TARGET_DIR/external-context-gatherer.md"
[ -e "$TARGET_DIR/librarian.md" ] && rm "$TARGET_DIR/librarian.md"
[ -e "$TARGET_DIR/local-context-gatherer.md" ] && rm "$TARGET_DIR/local-context-gatherer.md"
[ -e "$TARGET_DIR/reviewer.md" ] && rm "$TARGET_DIR/reviewer.md"
[ -e "$TARGET_DIR/security-reviewer.md" ] && rm "$TARGET_DIR/security-reviewer.md"
# [ -e "$TARGET_DIR/tester.md" ] && rm "$TARGET_DIR/tester.md"

ln -s "$SOURCE_DIR/Orchestrator.md" "$TARGET_DIR/Orchestrator.md"
ln -s "$SOURCE_DIR/subagents/"* "$TARGET_DIR/"
