TARGET_DIR="${1:-$HOME/.config/opencode/agents}"

rm "$TARGET_DIR/Orchestrator.md"
# rm "$TARGET_DIR/builder.md"
rm "$TARGET_DIR/coder.md"
rm "$TARGET_DIR/external-context-gatherer.md"
rm "$TARGET_DIR/librarian.md"
rm "$TARGET_DIR/local-context-gatherer.md"
rm "$TARGET_DIR/reviewer.md"
rm "$TARGET_DIR/security-reviewer.md"
# rm "$TARGET_DIR/tester.md"
